### ISSUE TITLE
Add Untappd button

### ISSUE THREAD

**Issue by dmofot** [sarahhenderson/Crafty-Social-Buttons#15]
@sarahhenderson - Possible enhancement, could you add an [Untappd](https://untappd.com/) icon?  It's social media for drinkers, ha.

![144](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_144.png) ![100](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_100.png) ![72](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_72.png) ![64](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_64.png) ![50](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_50.png) ![32](https://d1c8v1qci5en44.cloudfront.net/social/ut_icon_32.png)

**Comment by sarahhenderson** [comment]
I'd never even heard of that before, but I've added it to the backlog. Thanks!
