### ISSUE TITLE
Email button does not open in new window

### ISSUE THREAD

**Issue by martijeanp** [sarahhenderson/Crafty-Social-Buttons#17]
Hi Sarah.  I have the latest version of wordpress and your Craft Social media Buttons plugin.  I have checked the 'Open in new window' option, yet when I click the email button, it opens in the same tab/window ie my gmail account.  The other buttons shown are working as expected. 

If you have time to review and fix this I would appreciate it.  If you don't, please feel free to point me in the direction where I may update the code to does so.  

Thanks for a great plugin!

**Comment by sarahhenderson** [comment]
Thanks for the issue report.  I think this issue should be fixed in the latest version (1.4.1)
