### ISSUE TITLE
Options to select which counts should be displayed for facebook button

### ISSUE THREAD

**Issue by kepi** [sarahhenderson/Crafty-Social-Buttons#21]
Facebook API supports multiple metrics for they link stats. In Crafty Social Buttons it automatically choose `share_count` but it in certain cases user want to display different metric.

It would be great to be able to select which metric should display for Facebook in settings:

- share_count (default)
- like_count
- comment_count
- click_count
- total_count

Thanks for considering.

**Comment by sarahhenderson** [comment]
Thanks for this suggestion!  I've incorporated this into the latest update.  For now, I have given three options: shares only, shares + likes, or shares + likes + comments.
This is in update 1.5.4 which is currently live in the WordPress plugin gallery.

**Comment by kepi** [comment]
Thanks, working great!
